version: '3.8'
services:
  mongo_db:
    image: mongo:latest
    container_name: db_container
    restart: always
    volumes:
      - mongo_db:/data/db
    

  api: 
    build: .
    ports:
      - 5000:5000
    links:
      - mongo_db
    depends_on:
      - mongo_db
    environment:
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: users
      JWT_SECRET: pravand

volumes:
  mongo_db: {}
   